### PR TITLE
Added Issues + PR templates

### PR DESCRIPTION
**Pull request by Ayush7614**
This PR contains

* Adds a Issue Templates Bug and Feature the old Template was not looking good and not Perfect for the project
* Adds a PR Templates old one is not complete
* Correct all the position of folder and make all folder perfect

### CODE REVIEW

**Comment by Ayush7614** [comment]
@viferga Can you please have a look over the same? Thanks a lot!

**Comment by Ayush7614** [comment]
@viferga please have a look over the same

**Review by Siddhant-K-code — COMMENTED** [review]
I don't think, it is required!

**Comment by Ayush7614** [comment]
> I don't think, it is required!

@Siddhant-K-code actually the templates are not in the proper way that's why I am correct all the things and from this all things are correct if it is correct then please merge it

**Comment by viferga** [comment]
Sorry, I did not see this in a long time, @Ayush7614 I am merging it. Again sorry for the inconvenience. Whenever you want to find us easily you can go to our chats. And again, thanks for the PR and sorry about the time without merging.

**Pull request merged**
